project:
  type: website
  output-dir: docs

website:
  title: "Yechan Kim"
  favicon: gold-seal-real.png
  navbar:
    title: false
    logo: logo2-white.png
    right:
      - href: index.qmd
        text: Main
      - href: projects.qmd
        text: Current Projects
      - href: about.qmd
        text: About Me
      - href: CV.qmd
        text: Curriculum Vitae
  page-footer:
    background: light
    left: Copyright 2025, Yechan David Kim
    right: I built this website with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank} -- GO SUPPORT QUARTO

format:
  html:
    theme: styles.scss
    mainfont: Source Sans 3
    css: styles.css
    toc: false
    page-layout: full


editor: visual

